### ISSUE TITLE
App crashing on Android when local or remote video is on and try to move to different screen on the react native app

### ISSUE THREAD

**Issue by neeltrivedi** [aws-samples/amazon-chime-react-native-demo#111]
**Describe the bug**
The idea is that user is on a video call and can move to different screen to do his work on the same app.
NOTE: Video works okay if the app is in background. issue is when you move to different screen

**To Reproduce**
1. Have app with 3 screens (1st screen has link to go to 2nd screen. 2nd Screen has link to start video call that opens in Modal)
1. Go to 2nd screen
2. Click on Start video call
3. That should open modal with video enabled
4. Try minimizing the modal to go to 2nd screen 
5. See error

**Expected behavior**
Once you minimize modal, you should see 2nd screen and hear audio and video stream should be working

**Logs**
```
2021-10-06 11:46:10.981 2360-2360/com.xyz.testapp I/RNVideoViewManager: Creating view instance
2021-10-06 11:46:10.985 2360-2360/com.xyz.testapp I/RNVideoViewManager: Setting tileId: 2
2021-10-06 11:46:10.985 2360-2360/com.xyz.testapp I/DefaultVideoTileController: Binding VideoView to Tile with tileId = 2
2021-10-06 11:46:10.985 2360-2360/com.xyz.testapp I/DefaultVideoTileController: Initializing EGL state on EGL render view
2021-10-06 11:46:10.985 2360-2360/com.xyz.testapp I/SurfaceRenderView: Initializing render view
2021-10-06 11:46:10.987 2360-2436/com.xyz.testapp I/ChimeReactNativeSDKDemoManager: Called bindVideoView for tileId: 2 with identifier: 3063.0
2021-10-06 11:46:10.989 2360-2360/com.xyz.testapp I/DefaultEglRenderer: Initializing EGL renderer
2021-10-06 11:46:10.993 2360-2360/com.xyz.testapp I/DefaultVideoTile: Binding the View to Tile
2021-10-06 11:46:10.995 2360-2360/com.xyz.testapp D/SurfaceView: onWindowVisibilityChanged(0) true com.amazonaws.services.chime.sdk.meetings.audiovideo.video.DefaultVideoRenderView{2e1a56e V.E...... ......I. 0,0-0,0 #bf7} of ViewRootImpl@aec4622[MainActivity]
2021-10-06 11:46:10.995 2360-2360/com.xyz.testapp I/DefaultEglRenderer: Setting aspect ratio from 0.0 to 0.5660377
2021-10-06 11:46:11.008 2360-2360/com.xyz.testapp D/ViewRootImpl@aec4622[MainActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 543400910848} changed=false
2021-10-06 11:46:11.019 2360-2360/com.xyz.testapp D/SurfaceView: show() Surface(name=SurfaceView - com.xyz.testapp/com.xyz.testapp.MainActivity@2e1a56e@0[2360])/@0xb8f240f com.amazonaws.services.chime.sdk.meetings.audiovideo.video.DefaultVideoRenderView{2e1a56e V.E...... ......ID 0,96-1080,2004 #bf7}
2021-10-06 11:46:11.026 2360-3798/com.xyz.testapp I/SurfaceRenderView: Video frame rotated size changed to 960x540 with rotation Rotation0
2021-10-06 11:46:11.031 2360-2360/com.xyz.testapp D/SurfaceView: surfaceCreated 1 #8 com.amazonaws.services.chime.sdk.meetings.audiovideo.video.DefaultVideoRenderView{2e1a56e V.E...... ......ID 0,96-1080,2004 #bf7}
2021-10-06 11:46:11.031 2360-2360/com.xyz.testapp I/SurfaceRenderView: Surface created, creating EGL surface with resource
2021-10-06 11:46:11.031 2360-2360/com.xyz.testapp D/SurfaceView: surfaceChanged (1080,1908) 1 #8 com.amazonaws.services.chime.sdk.meetings.audiovideo.video.DefaultVideoRenderView{2e1a56e V.E...... ......ID 0,96-1080,2004 #bf7}
2021-10-06 11:46:11.032 2360-3820/com.xyz.testapp I/DefaultEglRenderer: Request on handler thread to create EGL surface from input surface Surface(name=null)/@0xcc0e6a5
2021-10-06 11:46:11.034 2360-3820/com.xyz.testapp D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2021-10-06 11:46:21.100 2360-2360/com.xyz.testapp D/ViewRootImpl@aec4622[MainActivity]: ViewPostIme pointer 0
2021-10-06 11:46:21.207 2360-2360/com.xyz.testapp D/ViewRootImpl@aec4622[MainActivity]: ViewPostIme pointer 1
2021-10-06 11:46:21.684 2360-2436/com.xyz.testapp I/ChimeReactNativeSDKDemoManager: Called bindVideoView for tileId: 2 with identifier: 3063.0
2021-10-06 11:46:21.702 2360-2360/com.xyz.testapp D/ViewRootImpl@aec4622[MainActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 543400910848} changed=false
2021-10-06 11:46:22.107 2360-2436/com.xyz.testapp I/ChimeReactNativeSDKDemoManager: Called bindVideoView for tileId: 2 with identifier: 3063.0
2021-10-06 11:46:22.124 2360-2360/com.xyz.testapp D/SurfaceView: show() Surface(name=SurfaceView - com.xyz.testapp/com.xyz.testapp.MainActivity@2e1a56e@0[2360])/@0xb8f240f com.amazonaws.services.chime.sdk.meetings.audiovideo.video.DefaultVideoRenderView{2e1a56e V.E...... ......ID 0,0-0,0 #bf7}
2021-10-06 11:46:22.124 2360-2360/com.xyz.testapp W/SurfaceComposerClient: SurfaceComposerClient::setSize: w, h [0, 0]
2021-10-06 11:46:22.124 2360-2360/com.xyz.testapp W/SurfaceComposerClient: SurfaceComposerClient::setSize: w, h [0, 0]
2021-10-06 11:46:22.143 2360-2360/com.xyz.testapp D/SurfaceView: surfaceChanged (0,0) 1 #5 com.amazonaws.services.chime.sdk.meetings.audiovideo.video.DefaultVideoRenderView{2e1a56e V.E...... ......ID 0,0-0,0 #bf7}
2021-10-06 11:46:22.144 2360-2360/com.xyz.testapp I/DefaultEglRenderer: Setting aspect ratio from 0.5660377 to NaN
2021-10-06 11:46:22.159 2360-2360/com.xyz.testapp D/SurfaceView: mHaveFrame: false com.amazonaws.services.chime.sdk.meetings.audiovideo.video.DefaultVideoRenderView{2e1a56e V.E...... ......ID 0,0-0,0 #bf7}
2021-10-06 11:46:22.189 2360-3820/com.xyz.testapp E/AndroidRuntime: FATAL EXCEPTION: EglRenderer
    Process: com.xyz.testapp, PID: 2360
    java.lang.IllegalArgumentException: Cannot round NaN value.
        at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:602)
        at com.amazonaws.services.chime.sdk.meetings.internal.video.gl.DefaultGlVideoFrameDrawer$calculateTransformedRenderSize$1.invoke(DefaultGlVideoFrameDrawer.kt:289)
        at com.amazonaws.services.chime.sdk.meetings.internal.video.gl.DefaultGlVideoFrameDrawer.calculateTransformedRenderSize(DefaultGlVideoFrameDrawer.kt:292)
        at com.amazonaws.services.chime.sdk.meetings.internal.video.gl.DefaultGlVideoFrameDrawer.drawFrame(DefaultGlVideoFrameDrawer.kt:205)
        at com.amazonaws.services.chime.sdk.meetings.internal.video.gl.DefaultEglRenderer.renderPendingFrame(DefaultEglRenderer.kt:227)
        at com.amazonaws.services.chime.sdk.meetings.internal.video.gl.DefaultEglRenderer.access$renderPendingFrame(DefaultEglRenderer.kt:26)
        at com.amazonaws.services.chime.sdk.meetings.internal.video.gl.DefaultEglRenderer$onVideoFrameReceived$1$1.invoke(DefaultEglRenderer.kt:160)
        at com.amazonaws.services.chime.sdk.meetings.internal.video.gl.DefaultEglRenderer$onVideoFrameReceived$1$1.invoke(DefaultEglRenderer.kt:26)
        at com.amazonaws.services.chime.sdk.meetings.internal.video.gl.DefaultEglRenderer$sam$i$java_lang_Runnable$0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2021-10-06 11:46:22.215 2360-2360/com.xyz.testapp D/SensorManager: unregisterListener ::   
2021-10-06 11:46:22.219 2360-3820/com.xyz.testapp I/Process: Sending signal. PID: 2360 SIG: 9
```

**Screenshots**

**Test environment Info (please complete the following information):**
 - Device: [Samsung s8]
 - OS: [e.g. Android 9]
 - Version amazon-chime-sdk: [e.g. 0.11.6]
 - Version amazon-chime-sdk-media: [e.g. 0.12.0]
 - Can you reproduce this in the demo app? (Did no try this)
If you are reporting a crash:
 - Please provide full crash logs.

**Additional context**

**Comment by neeltrivedi** [comment]
@ziyiz-amzn But i need to minimize my video screen so that i can do other stuff in the app. It works perfectly fine for iOS
