### ISSUE TITLE
native_window_api_connect failed (already connected to another API?)

### ISSUE THREAD

**Issue by raksha-mitel** [aws-samples/amazon-chime-react-native-demo#7]
I am using same DefaultRenderView to bind and unbind views. After some point getting below crash, if I set delay before binding view it works fine. But I don't want to do this,

2020-07-20 21:54:59.688 30296-31490/xxx.android E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0x6c46ff9010) failed (0xffffffed) (already connected to another API?)
2020-07-20 21:54:59.688 30296-31490/xxx.android E/libEGL: eglCreateWindowSurfaceTmpl:912 error 3003 (EGL_BAD_ALLOC)
2020-07-20 21:54:59.688 30296-31490/xxx.android E/AndroidRuntime: FATAL EXCEPTION: EglRenderer
    Process: xxx.android, PID: 30296
    java.lang.RuntimeException: Failed to create window surface: 0x3003
        at com.amazon.chime.webrtc.EglBase14.createSurfaceInternal(EglBase14.java:87)
        at com.amazon.chime.webrtc.EglBase14.createSurface(EglBase14.java:65)
        at com.amazon.chime.webrtc.EglRenderer$EglSurfaceCreation.run(EglRenderer.java:64)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)

chime sdk version = 0.5.3
media sdk version = 0.5.1

also observerved that onVideoTileRemoved(tileState : VideoTileState) getting called twice for the second time

Thanks in advance

**Comment by hokyungh** [comment]
Sorry for late reply. onVideoTileRemoved(tileState : VideoTileState) getting called twice should be fixed in the latest version. 

For the other issue, could you let us know your logic of binding/unbinding?
